name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "30 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: bahadjdz

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "🧊 Update 3D contribution graph"
            git push
          fi
