name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: bahadjdz
          outputs: |
            output/github-snake.svg?color_snake=#6DB3F2&color_dots=#0e75b6,#2ea44f,#f9f9f9
            output/github-snake-dark.svg?color_snake=#6DB3F2&color_dots=#0e75b6,#2ea44f,#FFFFFF&color_dot_6=#6DB3F2
          color_snake: "#6DB3F2"
          color_dots: "#0e75b6,#2ea44f,#f9f9f9"

      - name: Push Snake SVG to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
          destination_dir: ./
          keep_files: false
          commit_message: "🐍 Update contribution snake animation"
